name: Deploy to Forpsi (FTP)

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FORPSI_HOST }}
          username: ${{ secrets.FORPSI_USER }}
          password: ${{ secrets.FORPSI_PASS }}
          protocol: ftps
          port: 21
          server-dir: ${{ secrets.FORPSI_REMOTE_PATH }}
          local-dir: ./
          log-level: verbose
